Add manpage and ability to send messages to syslog for Sprinbatch SEL…
hubertqc/selinux_springbatch pull request #19
Opened 2024-09-13 11:14 UTC by Laurent-Gaillard

Closes #17  and #18
Add a man page in section 8 to document Springbatch SELinux module
Add a boolean (false by default) to allow Springbatch job to send messages to syslog

2024-09-13 20:31 UTC, hubertqc commented on manpages/man8/springbatch_selinux.8
> +Allows job running in the springbatch_t domain to connect to the SELinux (tcp) port service_name_port_t passed as its argument.
peut-être mettre service_name en italique dans `service_name_port_t`

2024-09-13 20:32 UTC, hubertqc commented on manpages/man8/springbatch_selinux.8
> +\fBspringbatch_allow_connectto(\fservice_name\fB)\R
Il manque un `R` après le `\f` dans les parenthèses, non ?

2024-09-13 20:32 UTC, hubertqc commented on manpages/man8/springbatch_selinux.8
> +Allows job running in the springbatch_t domain to consume (UDP/TCP) the network services linked ton SELinux port service_name_port_t passed as its argument.
cf supra

2024-09-14 06:49 UTC, Laurent-Gaillard commented on manpages/man8/springbatch_selinux.8
> +\fBspringbatch_allow_connectto(\fservice_name\fB)\R
Effectivement

2024-09-14 06:50 UTC, Laurent-Gaillard commented on manpages/man8/springbatch_selinux.8
> +Allows job running in the springbatch_t domain to connect to the SELinux (tcp) port service_name_port_t passed as its argument.
Fait

2024-09-14 06:50 UTC, Laurent-Gaillard commented on manpages/man8/springbatch_selinux.8
> +Allows job running in the springbatch_t domain to consume (UDP/TCP) the network services linked ton SELinux port service_name_port_t passed as its argument.
idem

2024-09-17 05:57 UTC, hubertqc commented on manpages/man8/springbatch_selinux.8
> +\fBspringbatch_allow_connectto(\fRservice_name\fB)\R
`\fR` tout à la fin pour faire le _reset_ non ?

2024-09-17 05:58 UTC, hubertqc approved these changes

2024-09-17 14:22 UTC, hubertqc requested changes
Correct the interface usage examples

2024-09-17 14:23 UTC, hubertqc approved these changes

2024-09-17 14:49 UTC, merged